### ISSUE TITLE
first build with some problems : c4log_setRustCallback not found and Undefined symbols 

### ISSUE THREAD

**Issue by cedseat** [Dushistov/couchbase-lite-rust#7]
Hi,

I try to clone and use your project but when I try to build it (on mac os) I have some problems :
- c4log_setRustCallback is not found
- note: Undefined symbols for architecture x86_64:
            "_C4CivetWebSocketFactory", referenced from:
                couchbase_lite::use_c4_civet_web_socket_factory::h07be68ed8ece27c2 in libcouchbase_lite-7a21ac095dc4f8d0.rlib(couchbase_lite-7a21ac095dc4f8d0.47fas814zwssgmh.rcgu.o)
          ld: symbol(s) not found for architecture x86_64

Thanks in advance
Cédric

**Comment by Dushistov** [comment]
Hi, @cedseat !

The problem is that websocket implementation shipped with libLiteCore is not available for mac os,
or it should be used in some other way in compare to Linux.
It is known issue, that's why I disable for now CI for mac os.
And for now only Linux is supported.

For long run I would like use Rust websocket implementation instead of shipped with libLiteCore,
so that's why I decide just disable CI for mac and don't care about this issue until Rust websocket come to play. 

But when I have time I will look at mac os build, may be it is possible to make some fast and dirty fix
to allow usage on mac.

**Comment by cedseat** [comment]
Thanks, what about callback? Ok I will look for the dirty fix and iI inform you if found something

**Comment by Dushistov** [comment]
> Thanks, what about callback?

It should work, see:

https://github.com/Dushistov/couchbase-lite-core/commit/96f1f3ba5e0c26b84dc5b4410904298fcc758dd0

I added  c4log_setRustCallback to C/c4.def , so it should not cause any problem.
On my macbook I got only: 
```
note: Undefined symbols for architecture x86_64:
            "_C4CivetWebSocketFactory", referenced from:
```
and that's all.

May be you forget `git submodule update --init --recursive` ?

**Comment by cedseat** [comment]
Ah ok! It's me i clone manually the project libcore not from your submodules Dirk, sorry

**Comment by Dushistov** [comment]
There is problem with `va_list` usage in Rust and I am not sure that couchbase team accept my PR about log callback without `va_list`, so for now I make fork. I hope in near future Rust will support va_list so there is no need for fork.

**Comment by cedseat** [comment]
Perhaps this crate is a solution ? https://github.com/thepowersgang/va_list-rs

**Comment by Dushistov** [comment]
> Perhaps this crate is a solution ?

Yes, I know about this crate, but list of architectures supported by crate (you can see it via directory listing 
https://github.com/thepowersgang/va_list-rs/tree/master/src) as not big as I want. 

Yes, at now only Linux is supported, but in long run I want support the all platforms where possible to build libLiteCore. Plus this crate is not very popular, so it is not really good tested.

But if rust-lang/rust#44930 is really stuck I will have to reconsider usage of va_list-rs

**Comment by cedseat** [comment]
About build on macos I have solution. It's necessary to copy differents static library as FleeceStatic, Support, BLIPStatic, SQLite3_UnicodeSN and CivetWeb in target dir and add cargo:rust-link parameters to link with its. I'm curious, how you can build on linux without those static library?

**Comment by Dushistov** [comment]
@cedseat 

> I'm curious, how you can build on linux without those static library?

I do not link libLiteCore as static library. I link with shared library. It includes all static libraries as you listed above. 

There is perfect reason for it - sqlite. 
In addition to couchbase-lite-core I use sqlite via https://github.com/jgallagher/rusqlite ,
and it is very hard to mix two libraries system sqlite and sqlite from libLiteCore in the same binary if both linked statically. It would be link error or worst (and more probable) that linker pick up random symbols from random library: `sqlite3_open` from system sqlite for example and `sqlite3_close` from `SQLite3_UnicodeSN` you would see random crashes.

You can see `build.rs` this in couchbase-lite-core-sys/build.rs: dll for windows, dylib for mac and so library for linux.

As I understand `CivetWeb` doesn't include for some reason into libLiteCore.dylib shared library. Because of I tried unmask its symbols in C/c4.def when CI failed, but without any success.

**Comment by cedseat** [comment]
In my test the liblitecore stay dylib but the build don't found some symbols that are in vendors libs. So I try to add those vendore in link static params and the build success

**Comment by Dushistov** [comment]
C/c4.def is list of public symbols in .dylib, other symbols will be hidden by linker.
When I try to fix mac os CI error, I add one civetweb symbol to this list, 
but it should be added more symbols. On Linux there is no such mechanizm to hide symbols (see couchbase/couchbase-lite-core#845 ), so may be that's why the problem with mac os.
